import { randomUUID } from 'node:crypto'
import { RECEBIMENTO_STATUS, STATUS_TRANSITIONS, ROLE_STATUS_PERMISSIONS, DOCUMENT_TYPE_OPTIONS, UNIT_OPTIONS, RECEIPT_TYPE_OPTIONS, SUPPLIER_OPTIONS, DIVERGENCE_TYPE_OPTIONS, STATUS_OPTIONS } from '../../src/data.js'

const now = () => new Date().toISOString()
const uid = (prefix) => `${prefix}-${randomUUID()}`
export const actor = (user) => ({ id: user.id, nome: user.nome || user.name, name: user.name || user.nome, iniciais: user.iniciais, perfil: user.perfil || user.role, role: user.role || user.perfil })
export const isAdmin = (user) => (user.perfil || user.role) === 'Administrador'
export const canWrite = (user) => (user.perfil || user.role) !== 'Consulta'

export function catalogos() {
  return { status: STATUS_OPTIONS, unidades: UNIT_OPTIONS, tiposRecebimento: RECEIPT_TYPE_OPTIONS, fornecedores: SUPPLIER_OPTIONS, tiposDocumento: DOCUMENT_TYPE_OPTIONS, tiposDivergencia: DIVERGENCE_TYPE_OPTIONS }
}
export function permissions(user) {
  const role = user.perfil || user.role
  if (role === 'Consulta') return ['recebimentos.read', 'itens.read', 'anexos.read', 'divergencias.read', 'historico.read']
  return ['recebimentos.read', 'recebimentos.create', 'recebimentos.update', 'itens.read', 'itens.write', 'anexos.read', 'anexos.write', 'divergencias.read', 'divergencias.write', 'status.write', ...(role === 'Administrador' ? ['recebimentos.archive', 'usuarios.write', 'auditoria.read'] : [])]
}
function audit(receipt, user, acao, detalhes) { receipt.historicoAlteracoes = [...(receipt.historicoAlteracoes || []), { id: uid('AUD'), data: now(), usuario: actor(user), acao, detalhes }] }
function statusHistory(receipt, user, de, para, observacao = '') { receipt.historicoStatus = [...(receipt.historicoStatus || []), { id: uid('HST'), data: now(), usuario: actor(user), de, para, observacao }] }
function openDivs(receipt) { return (receipt.divergencias || []).filter((entry) => !entry.resolvida) }
function isNfPending(receipt) { return !receipt?.numeroNf || !(receipt.anexos || []).some((entry) => entry.categoria === 'Nota Fiscal' && !entry.removido) }
function normalizeItem(input = {}, index = 0) { const received = Number(input.quantidadeRecebida ?? input.quantidade ?? 0) || 0; return { id: input.id || uid('IT'), numero: String(input.numero ?? input.item ?? (index + 1) * 10), codigo: String(input.codigo ?? '').trim(), descricao: String(input.descricao ?? '').trim(), quantidadeSolicitada: Number(input.quantidadeSolicitada ?? received) || 0, quantidadeRecebida: received, unidade: input.unidade || 'UN' } }
function receiptOrThrow(receipt) { if (!receipt) { const error = new Error('Recebimento não encontrado.'); error.code = 'RECEIPT_NOT_FOUND'; error.status = 404; throw error } return receipt }
function forbidden(message) { const error = new Error(message); error.code = 'FORBIDDEN'; error.status = 403; throw error }
function conflict(code, message) { const error = new Error(message); error.code = code; error.status = 409; throw error }
function validationError(message, details) { const error = new Error(message); error.code = 'VALIDATION_ERROR'; error.status = 422; error.details = details; throw error }

function validateReceiptInput(input, partial = false) {
  const errors = {}
  if (!partial || 'pedido' in input) if (!String(input.pedido || '').trim()) errors.pedido = 'Pedido é obrigatório.'
  if (!partial || 'fornecedor' in input) if (!String(input.fornecedor || '').trim()) errors.fornecedor = 'Fornecedor é obrigatório.'
  if (!partial || 'dataRecebimento' in input) if (!/^\d{4}-\d{2}-\d{2}$/.test(String(input.dataRecebimento || ''))) errors.dataRecebimento = 'Data de recebimento inválida.'
  if ('tipo' in input && !RECEIPT_TYPE_OPTIONS.some((option) => option.value === input.tipo)) errors.tipo = 'Tipo de recebimento inválido.'
  if ('cnpjFornecedor' in input && input.cnpjFornecedor && !/^\d{2}\.?(\d{3})\.?\d{3}\/?\d{4}-?\d{2}$/.test(String(input.cnpjFornecedor))) errors.cnpjFornecedor = 'CNPJ do fornecedor inválido.'
  if ('itens' in input) {
    if (!Array.isArray(input.itens)) errors.itens = 'Itens deve ser uma lista.'
    else input.itens.forEach((item, index) => { if (!String(item.descricao || '').trim()) errors[`itens.${index}.descricao`] = 'Descrição do item é obrigatória.'; if (!UNIT_OPTIONS.some((option) => option.value === item.unidade)) errors[`itens.${index}.unidade`] = 'Unidade inválida.'; if (Number(item.quantidadeRecebida) < 0 || Number(item.quantidadeSolicitada) < 0) errors[`itens.${index}.quantidade`] = 'Quantidade não pode ser negativa.' })
  }
  if (Object.keys(errors).length) validationError('Dados do recebimento inválidos.', errors)
}
function nextProtocol(recebimentos, date) { const year = String(date || now()).slice(0, 4); const expression = new RegExp(`^REC-${year}-(\\d+)$`); const max = recebimentos.reduce((value, entry) => Math.max(value, Number(String(entry.protocolo || '').match(expression)?.[1] || 0)), 0); return `REC-${year}-${String(max + 1).padStart(4, '0')}` }
function requireWritable(user) { if (!canWrite(user)) forbidden('O perfil Consulta não pode alterar dados.') }
function requireOpenForEdit(receipt, user, message = 'Recebimento finalizado.') { if (receipt.status === RECEBIMENTO_STATUS.FINALIZADO && !isAdmin(user)) forbidden(message) }

export function createRecebimento(input, user, allRecebimentos) {
  requireWritable(user); validateReceiptInput(input)
  const timestamp = now(); const date = input.dataRecebimento || timestamp.slice(0, 10); const protocolo = input.protocolo || nextProtocol(allRecebimentos, date)
  if (allRecebimentos.some((entry) => entry.protocolo === protocolo)) conflict('PROTOCOL_EXISTS', 'Protocolo já existe.')
  const receipt = { id: input.id || protocolo, protocolo, pedido: String(input.pedido || '').trim(), numeroNf: String(input.numeroNf || '').trim() || null, serieNf: String(input.serieNf || '').trim() || null, dataRecebimento: date, fornecedor: String(input.fornecedor || '').trim(), cnpjFornecedor: String(input.cnpjFornecedor || '').trim(), tipo: input.tipo || 'Estoque', responsavel: actor(user), status: RECEBIMENTO_STATUS.DIGITACAO, observacoes: String(input.observacoes || '').trim(), criadoEm: timestamp, atualizadoEm: timestamp, itens: (input.itens || []).map(normalizeItem), anexos: [], divergencias: [], historicoStatus: [], historicoAlteracoes: [], arquivado: false }
  statusHistory(receipt, user, null, receipt.status, 'Registro criado.'); audit(receipt, user, 'Recebimento criado', `Protocolo ${protocolo}.`); return receipt
}
export function updateRecebimento(receipt, input, user) { receiptOrThrow(receipt); requireWritable(user); requireOpenForEdit(receipt, user, 'Somente um administrador pode editar um recebimento finalizado.'); validateReceiptInput(input, true); const blocked = new Set(['id', 'protocolo', 'responsavel', 'status', 'historicoStatus', 'historicoAlteracoes', 'criadoEm', 'anexos', 'divergencias']); const changes = Object.fromEntries(Object.entries(input).filter(([key]) => !blocked.has(key))); if ('numeroNf' in changes) changes.numeroNf = String(changes.numeroNf || '').trim() || null; if ('serieNf' in changes) changes.serieNf = String(changes.serieNf || '').trim() || null; if ('pedido' in changes) changes.pedido = String(changes.pedido || '').trim(); Object.assign(receipt, changes, { atualizadoEm: now() }); audit(receipt, user, 'Dados alterados', `Campos atualizados: ${Object.keys(changes).join(', ')}.`); return receipt }
export function addItem(receipt, input, user) { receiptOrThrow(receipt); requireWritable(user); requireOpenForEdit(receipt, user); const item = normalizeItem(input, (receipt.itens || []).length); receipt.itens = [...(receipt.itens || []), item]; receipt.atualizadoEm = now(); audit(receipt, user, 'Item incluído', item.descricao || item.numero); return item }
export function updateItem(receipt, itemId, input, user) { receiptOrThrow(receipt); requireWritable(user); requireOpenForEdit(receipt, user); const index = (receipt.itens || []).findIndex((entry) => entry.id === itemId); if (index < 0) { const error = new Error('Item não encontrado.'); error.code = 'ITEM_NOT_FOUND'; error.status = 404; throw error }; const item = normalizeItem({ ...receipt.itens[index], ...input }, index); receipt.itens[index] = item; receipt.atualizadoEm = now(); audit(receipt, user, 'Item alterado', item.descricao || item.numero); return item }
export function removeItem(receipt, itemId, user) { receiptOrThrow(receipt); requireWritable(user); requireOpenForEdit(receipt, user); if ((receipt.divergencias || []).some((entry) => entry.itemId === itemId)) conflict('ITEM_HAS_DIVERGENCE', 'O item possui divergências vinculadas e não pode ser removido.'); const index = (receipt.itens || []).findIndex((entry) => entry.id === itemId); if (index < 0) { const error = new Error('Item não encontrado.'); error.code = 'ITEM_NOT_FOUND'; error.status = 404; throw error }; const [item] = receipt.itens.splice(index, 1); receipt.atualizadoEm = now(); audit(receipt, user, 'Item removido', item.descricao || item.numero); return item }
export function addAttachment(receipt, input, storageKey, user) { receiptOrThrow(receipt); requireWritable(user); requireOpenForEdit(receipt, user); const attachment = { id: uid('ANX'), nome: String(input.name || 'arquivo'), categoria: input.categoria || 'Outro', tipo: input.categoria || 'Outro', mimeType: input.mimeType || 'application/octet-stream', tamanho: Number(input.size || 0), dataInclusao: now(), incluidoPor: actor(user), storageKey, url: `/api/v1/anexos/${storageKey}/download`, removido: false }; receipt.anexos = [...(receipt.anexos || []), attachment]; receipt.atualizadoEm = now(); audit(receipt, user, 'Arquivo incluído', attachment.nome); return attachment }
export function removeAttachment(receipt, attachmentId, reason, user) { receiptOrThrow(receipt); requireWritable(user); requireOpenForEdit(receipt, user); const attachment = (receipt.anexos || []).find((entry) => entry.id === attachmentId); if (!attachment) { const error = new Error('Arquivo não encontrado.'); error.code = 'ATTACHMENT_NOT_FOUND'; error.status = 404; throw error }; attachment.removido = true; attachment.removidoEm = now(); attachment.removidoPor = actor(user); attachment.motivoRemocao = reason || ''; receipt.atualizadoEm = now(); audit(receipt, user, 'Arquivo removido', attachment.nome); return attachment }
export function addDivergence(receipt, input, user) { receiptOrThrow(receipt); requireWritable(user); requireOpenForEdit(receipt, user); const descricao = String(input.descricao || '').trim(); if (!descricao) validationError('Descreva a divergência encontrada.'); if (input.itemId && !(receipt.itens || []).some((entry) => entry.id === input.itemId)) validationError('O item vinculado à divergência não foi encontrado.'); const divergence = { id: uid('DIV'), tipo: input.tipo || 'Outro', descricao, itemId: input.itemId || null, criadaEm: now(), criadaPor: actor(user), resolvida: false, resolvidaEm: null, resolvidaPor: null, resolucao: '' }; receipt.divergencias = [...(receipt.divergencias || []), divergence]; if (receipt.status === RECEBIMENTO_STATUS.CONFERENCIA) { statusHistory(receipt, user, receipt.status, RECEBIMENTO_STATUS.DIVERGENCIA, 'Divergência registrada.'); receipt.status = RECEBIMENTO_STATUS.DIVERGENCIA }; receipt.atualizadoEm = now(); audit(receipt, user, 'Divergência registrada', `${divergence.tipo}: ${descricao}`); return divergence }
export function resolveDivergence(receipt, divergenceId, input, user) { receiptOrThrow(receipt); requireWritable(user); const divergence = (receipt.divergencias || []).find((entry) => entry.id === divergenceId); if (!divergence) { const error = new Error('Divergência não encontrada.'); error.code = 'DIVERGENCE_NOT_FOUND'; error.status = 404; throw error }; const resolution = String(input.resolucao || input.resolution || '').trim(); if (!resolution) validationError('Informe como a divergência foi resolvida.'); divergence.resolvida = true; divergence.resolvidaEm = now(); divergence.resolvidaPor = actor(user); divergence.resolucao = resolution; receipt.atualizadoEm = now(); audit(receipt, user, 'Divergência resolvida', resolution); return divergence }
export function reopenDivergence(receipt, divergenceId, input, user) { receiptOrThrow(receipt); requireWritable(user); const divergence = (receipt.divergencias || []).find((entry) => entry.id === divergenceId); if (!divergence) { const error = new Error('Divergência não encontrada.'); error.code = 'DIVERGENCE_NOT_FOUND'; error.status = 404; throw error }; divergence.resolvida = false; divergence.resolvidaEm = null; divergence.resolvidaPor = null; divergence.resolucao = ''; receipt.atualizadoEm = now(); audit(receipt, user, 'Divergência reaberta', input.reason || divergence.descricao); return divergence }
export function transitionStatus(receipt, input, user) { receiptOrThrow(receipt); requireWritable(user); const next = input.status; let reason = !STATUS_OPTIONS.some((option) => option.value === next) ? 'Status inválido.' : receipt.status === next ? 'O recebimento já está neste status.' : null; if (!reason && !isAdmin(user) && !(STATUS_TRANSITIONS[receipt.status] || []).includes(next)) reason = 'Essa mudança não faz parte do fluxo permitido.'; if (!reason && !isAdmin(user) && !(ROLE_STATUS_PERMISSIONS[user.perfil || user.role] || []).includes(next)) reason = `O perfil ${user.perfil || user.role} não pode mover para este status.`; if (!reason && next === RECEBIMENTO_STATUS.DIVERGENCIA && !openDivs(receipt).length) reason = 'Registre uma divergência aberta antes de mudar o status.'; if (!reason && next === RECEBIMENTO_STATUS.FINALIZADO && isNfPending(receipt)) reason = 'A NF e seu arquivo são obrigatórios para finalizar.'; if (!reason && next === RECEBIMENTO_STATUS.FINALIZADO && !(receipt.itens || []).length) reason = 'Inclua ao menos um item para finalizar.'; if (!reason && next === RECEBIMENTO_STATUS.FINALIZADO && openDivs(receipt).length) reason = 'Resolva todas as divergências antes de finalizar.'; if (reason && !input.force) validationError(reason); if (input.force && !isAdmin(user)) forbidden('Somente administrador pode forçar transições.'); const previous = receipt.status; receipt.status = next; receipt.atualizadoEm = now(); statusHistory(receipt, user, previous, next, input.observacao || input.note || ''); audit(receipt, user, 'Status alterado', `${previous} → ${next}.`); return { recebimentoId: receipt.id, statusAnterior: previous, status: next, alteradoPor: actor(user), alteradoEm: receipt.atualizadoEm } }
export function archive(receipt, reason, user) { receiptOrThrow(receipt); if (!isAdmin(user)) forbidden('Somente um administrador pode arquivar registros.'); receipt.arquivado = true; receipt.arquivadoEm = now(); receipt.arquivadoPor = actor(user); receipt.atualizadoEm = now(); audit(receipt, user, 'Recebimento arquivado', reason || 'Sem motivo informado.'); return receipt }
export function restore(receipt, user) { receiptOrThrow(receipt); if (!isAdmin(user)) forbidden('Somente um administrador pode restaurar registros.'); receipt.arquivado = false; receipt.restauradoEm = now(); receipt.atualizadoEm = now(); audit(receipt, user, 'Recebimento restaurado', receipt.protocolo); return receipt }
export function dashboard(recebimentos) { const rows = recebimentos.filter((entry) => !entry.arquivado); const counts = Object.fromEntries(STATUS_OPTIONS.map((status) => [status.value, rows.filter((entry) => entry.status === status.value).length])); return { total: rows.length, status: counts, nfPendentes: rows.filter(isNfPending).length, divergencias: rows.filter((entry) => openDivs(entry).length > 0).length } }
