import http from 'node:http'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { randomUUID } from 'node:crypto'
import { DEMO_USERS } from '../src/data.js'
import { readEnvironment } from './config/env.mjs'
import { createGoogleSheetsClient } from './integrations/googleSheets.mjs'
import { createRecebimentosRepository } from './repositories/recebimentosRepository.mjs'
import * as service from './services/recebimentosService.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const env = readEnvironment()
const uploadDir = env.uploadDir || path.join(__dirname, 'uploads')
const repository = createRecebimentosRepository({ sheets: createGoogleSheetsClient(env.google), defaultUsers: DEMO_USERS })
const json = (res, status, body, headers = {}) => { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...headers }); res.end(JSON.stringify(body)) }
const error = (res, status, code, message, details) => json(res, status, { error: { code, message, ...(details ? { details } : {}) } })
const routeParts = (url) => url.pathname.replace(/^\/api\/v1\/?/, '').split('/').filter(Boolean)
const parseUrl = (req) => new URL(req.url, `http://${req.headers.host || 'localhost'}`)
async function body(req) { const chunks = []; for await (const chunk of req) chunks.push(chunk); const raw = Buffer.concat(chunks).toString('utf8'); if (!raw) return {}; try { return JSON.parse(raw) } catch { const exception = new Error('JSON inválido.'); exception.status = 400; exception.code = 'INVALID_JSON'; throw exception } }
async function requestUser(req, res) { const user = await repository.getUsuario(req.headers['x-user-id'] || DEMO_USERS[0]?.id); if (!user) { error(res, 401, 'UNAUTHORIZED', 'Usuário não autenticado.'); return null } return user }
function writeGuard(user, res) { if (service.canWrite(user)) return true; error(res, 403, 'FORBIDDEN', 'O perfil Consulta não pode alterar dados.'); return false }
function receiptOr404(res, receipt) { if (receipt) return receipt; error(res, 404, 'RECEIPT_NOT_FOUND', 'Recebimento não encontrado.'); return null }
function listFiltered(recebimentos, search) { let rows = search.get('includeArchived') === 'true' ? recebimentos : recebimentos.filter((entry) => !entry.arquivado); const q = (search.get('q') || '').toLowerCase().trim(); const status = search.get('status'); const fornecedor = search.get('fornecedor'); const pedido = search.get('pedido'); const nf = search.get('numeroNf'); if (q) rows = rows.filter((entry) => JSON.stringify(entry).toLowerCase().includes(q)); if (status) rows = rows.filter((entry) => entry.status === status); if (fornecedor) rows = rows.filter((entry) => entry.fornecedor === fornecedor); if (pedido) rows = rows.filter((entry) => entry.pedido === pedido); if (nf) rows = rows.filter((entry) => entry.numeroNf === nf); const orderBy = search.get('orderBy') || 'dataRecebimento'; const dir = search.get('order') === 'asc' ? 1 : -1; rows = [...rows].sort((a, b) => String(a[orderBy] || '').localeCompare(String(b[orderBy] || '')) * dir); const page = Math.max(1, Number(search.get('page') || 1)); const pageSize = Math.min(100, Math.max(1, Number(search.get('pageSize') || 50))); return { data: rows.slice((page - 1) * pageSize, page * pageSize), pagination: { page, pageSize, total: rows.length, totalPages: Math.max(1, Math.ceil(rows.length / pageSize)) } } }
const save = async (receipt) => repository.updateRecebimento(receipt)

async function handle(req, res) {
  const url = parseUrl(req); const parts = routeParts(url)
  if (req.method === 'OPTIONS') { res.writeHead(204, { 'Access-Control-Allow-Origin': env.corsOrigin, 'Access-Control-Allow-Headers': 'Content-Type, X-User-Id', 'Access-Control-Allow-Methods': 'GET,POST,PATCH,DELETE,OPTIONS' }); return res.end() }
  if (!url.pathname.startsWith('/api/v1')) return error(res, 404, 'NOT_FOUND', 'Rota não encontrada.')
  try {
    const user = await requestUser(req, res); if (!user) return
    if (parts.join('/') === 'auth/me' && req.method === 'GET') return json(res, 200, { ...service.actor(user), email: user.email, permissoes: service.permissions(user) })
    if (parts.join('/') === 'catalogos' && req.method === 'GET') return json(res, 200, service.catalogos())
    if (parts.join('/') === 'usuarios' && req.method === 'GET') return json(res, 200, { data: await repository.listUsuarios() })
    if (parts.join('/') === 'usuarios' && req.method === 'POST') { if (!service.isAdmin(user)) return error(res, 403, 'FORBIDDEN', 'Somente administrador pode criar usuários.'); const input = await body(req); if (!input.nome || !input.email || !input.perfil) return error(res, 422, 'VALIDATION_ERROR', 'Nome, e-mail e perfil são obrigatórios.'); if (!['Administrador', 'Almoxarifado', 'Suprimentos', 'Consulta'].includes(input.perfil)) return error(res, 422, 'VALIDATION_ERROR', 'Perfil inválido.'); const created = { id: input.id || `USR-${randomUUID()}`, nome: String(input.nome).trim(), name: String(input.nome).trim(), iniciais: String(input.nome).split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase(), email: String(input.email).trim(), perfil: input.perfil, role: input.perfil, ativo: input.ativo !== false }; await repository.saveUsuario(created); return json(res, 201, created) }
    if (parts[0] === 'usuarios' && parts.length === 2 && req.method === 'GET') { const target = await repository.getUsuario(parts[1]); return target ? json(res, 200, target) : error(res, 404, 'USER_NOT_FOUND', 'Usuário não encontrado.') }
    if (parts[0] === 'usuarios' && parts.length === 2 && req.method === 'PATCH') { if (!service.isAdmin(user)) return error(res, 403, 'FORBIDDEN', 'Somente administrador pode editar usuários.'); const target = await repository.getUsuario(parts[1]); if (!target) return error(res, 404, 'USER_NOT_FOUND', 'Usuário não encontrado.'); const input = await body(req); if (input.perfil && !['Administrador', 'Almoxarifado', 'Suprimentos', 'Consulta'].includes(input.perfil)) return error(res, 422, 'VALIDATION_ERROR', 'Perfil inválido.'); Object.assign(target, input, { id: target.id }); target.name = target.nome; target.role = target.perfil; await repository.saveUsuario(target); return json(res, 200, target) }
    if (parts.join('/') === 'recebimentos' && req.method === 'GET') return json(res, 200, listFiltered(await repository.listRecebimentos(), url.searchParams))
    if (parts.join('/') === 'recebimentos' && req.method === 'POST') { if (!writeGuard(user, res)) return; const created = service.createRecebimento(await body(req), user, await repository.listRecebimentos()); await repository.createRecebimento(created); return json(res, 201, created) }
    if (parts[0] === 'recebimentos' && parts.length === 2 && req.method === 'GET') { const receipt = await repository.getRecebimento(parts[1]); return receipt ? json(res, 200, receipt) : error(res, 404, 'RECEIPT_NOT_FOUND', 'Recebimento não encontrado.') }
    if (parts[0] === 'recebimentos' && parts.length === 2 && req.method === 'PATCH') { if (!writeGuard(user, res)) return; const receipt = receiptOr404(res, await repository.getRecebimento(parts[1])); if (!receipt) return; service.updateRecebimento(receipt, await body(req), user); await save(receipt); return json(res, 200, receipt) }
    if (parts[0] === 'recebimentos' && parts[2] === 'itens') { const receipt = receiptOr404(res, await repository.getRecebimento(parts[1])); if (!receipt) return; if (req.method === 'GET' && parts.length === 3) return json(res, 200, { data: receipt.itens || [] }); if (!writeGuard(user, res)) return; if (req.method === 'POST' && parts.length === 3) { const item = service.addItem(receipt, await body(req), user); await save(receipt); return json(res, 201, item) } if (parts.length === 4 && req.method === 'PATCH') { const item = service.updateItem(receipt, parts[3], await body(req), user); await save(receipt); return json(res, 200, item) } if (parts.length === 4 && req.method === 'DELETE') { const item = service.removeItem(receipt, parts[3], user); await save(receipt); return json(res, 200, item) } }
    if (parts[0] === 'recebimentos' && parts[2] === 'anexos') { const receipt = receiptOr404(res, await repository.getRecebimento(parts[1])); if (!receipt) return; if (req.method === 'GET' && parts.length === 3) return json(res, 200, { data: (receipt.anexos || []).filter((entry) => !entry.removido) }); if (!writeGuard(user, res)) return; if (req.method === 'POST' && parts.length === 3) { const input = await body(req); if (!input.dataBase64) return error(res, 422, 'FILE_REQUIRED', 'Arquivo obrigatório.'); const buffer = Buffer.from(input.dataBase64, 'base64'); if (buffer.length > 15 * 1024 * 1024) return error(res, 422, 'FILE_TOO_LARGE', 'Arquivo excede 15 MB.'); const safeName = String(input.name || 'arquivo').replace(/[^a-zA-Z0-9._-]/g, '_'); const storageKey = `FILE-${randomUUID()}-${safeName}`; await fs.writeFile(path.join(uploadDir, storageKey), buffer); const attachment = service.addAttachment(receipt, input, storageKey, user); await save(receipt); return json(res, 201, attachment) } if (parts.length === 4 && req.method === 'DELETE') { const attachment = service.removeAttachment(receipt, parts[3], (await body(req)).reason, user); await save(receipt); return json(res, 200, attachment) } }
    if (parts[0] === 'recebimentos' && parts[2] === 'divergencias') { const receipt = receiptOr404(res, await repository.getRecebimento(parts[1])); if (!receipt) return; if (req.method === 'GET' && parts.length === 3) return json(res, 200, { data: receipt.divergencias || [] }); if (!writeGuard(user, res)) return; if (req.method === 'POST' && parts.length === 3) { const divergence = service.addDivergence(receipt, await body(req), user); await save(receipt); return json(res, 201, divergence) } if (parts.length === 5 && parts[4] === 'resolver' && req.method === 'POST') { const divergence = service.resolveDivergence(receipt, parts[3], await body(req), user); await save(receipt); return json(res, 200, divergence) } if (parts.length === 5 && parts[4] === 'reabrir' && req.method === 'POST') { const divergence = service.reopenDivergence(receipt, parts[3], await body(req), user); await save(receipt); return json(res, 200, divergence) } }
    if (parts[0] === 'recebimentos' && parts[2] === 'status' && parts.length === 3 && req.method === 'POST') { if (!writeGuard(user, res)) return; const receipt = receiptOr404(res, await repository.getRecebimento(parts[1])); if (!receipt) return; const result = service.transitionStatus(receipt, await body(req), user); await save(receipt); return json(res, 200, result) }
    if (parts[0] === 'recebimentos' && parts[2] === 'historico' && parts[3] === 'status' && req.method === 'GET') { const receipt = receiptOr404(res, await repository.getRecebimento(parts[1])); return receipt && json(res, 200, { data: receipt.historicoStatus || [] }) }
    if (parts[0] === 'recebimentos' && parts[2] === 'historico' && parts[3] === 'auditoria' && req.method === 'GET') { const receipt = receiptOr404(res, await repository.getRecebimento(parts[1])); return receipt && json(res, 200, { data: receipt.historicoAlteracoes || [] }) }
    if (parts[0] === 'recebimentos' && parts[2] === 'arquivar' && parts.length === 3 && req.method === 'POST') { const receipt = receiptOr404(res, await repository.getRecebimento(parts[1])); if (!receipt) return; service.archive(receipt, (await body(req)).reason, user); await save(receipt); return json(res, 200, receipt) }
    if (parts[0] === 'recebimentos' && parts[2] === 'restaurar' && parts.length === 3 && req.method === 'POST') { const receipt = receiptOr404(res, await repository.getRecebimento(parts[1])); if (!receipt) return; service.restore(receipt, user); await save(receipt); return json(res, 200, receipt) }
    if (parts.join('/') === 'dashboard' && req.method === 'GET') return json(res, 200, service.dashboard(await repository.listRecebimentos()))
    if (parts[0] === 'anexos' && parts.length === 3 && parts[2] === 'download' && req.method === 'GET') { const file = path.join(uploadDir, path.basename(parts[1])); try { const stat = await fs.stat(file); res.writeHead(200, { 'Content-Length': stat.size, 'Content-Type': 'application/octet-stream', 'Access-Control-Allow-Origin': env.corsOrigin }); return res.end(await fs.readFile(file)) } catch { return error(res, 404, 'FILE_NOT_FOUND', 'Arquivo não encontrado.') } }
    return error(res, 404, 'NOT_FOUND', 'Endpoint não encontrado.')
  } catch (exception) { console.error(exception); return error(res, exception.status || 500, exception.code || 'INTERNAL_ERROR', exception.message || 'Erro interno.', exception.details) }
}

await fs.mkdir(uploadDir, { recursive: true })
await repository.initialize()
http.createServer((req, res) => { res.setHeader('Access-Control-Allow-Origin', env.corsOrigin); handle(req, res) }).listen(env.port, env.host, () => console.log(`ALM API em http://${env.host}:${env.port}/api/v1`))
